# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "comments", :force => true do |t|
    t.column "comment",    :text
    t.column "game_id",    :integer
    t.column "created_on", :datetime
    t.column "user_id",    :integer
  end

  create_table "games", :force => true do |t|
    t.column "lg_game_num",       :integer
    t.column "result",            :string,   :limit => 1
    t.column "lg_data",           :text
    t.column "created_on",        :datetime
    t.column "last_commented_on", :datetime
    t.column "last_commented_by", :integer
    t.column "player1",           :string
    t.column "player2",           :string
    t.column "winner",            :integer
    t.column "tournament",        :string
  end

  add_index "games", ["lg_game_num"], :name => "index_games_on_lg_game_num", :unique => true

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "created_on",      :datetime
    t.column "on_lg",           :boolean
    t.column "name_on_lg",      :string
    t.column "info",            :text
  end

end
